//Generated by GuiGenie - Copyright @ Platypus
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.event.*;

public class PlatypusGUI extends JPanel {
    private JButton jcomp1;
    private JLabel jcomp2;
    private JList Solutions;
    private JLabel jcomp4;
    private JMenuBar jcomp5;
    private JLabel jcomp6;
    private JList jcomp7;

    public PlatypusGUI() {
        //construct preComponents
        String[] SolutionsItems = {"Solution 1", "Solution 2", "Solution 3"};
        JMenu helpMenu = new JMenu ("Help");
        JMenuItem contentsItem = new JMenuItem ("Contents");
        helpMenu.add (contentsItem);
        JMenuItem aboutItem = new JMenuItem ("About");
        helpMenu.add (aboutItem);
        String[] jcomp7Items = {"ISSUES WILL BE DISPLAYED HERE"};

        //construct components
        jcomp1 = new JButton ("SCAN");
        jcomp2 = new JLabel (" Click scan to scan your device for any potential issues. The results will be displayed in the scrollbox to the right, with possible solutions for your system's issues.");
        Solutions = new JList (SolutionsItems);
        jcomp4 = new JLabel (" Welcome to P.L.A.T.Y.P.U.S.");
        jcomp5 = new JMenuBar();
        jcomp5.add (helpMenu);
        jcomp6 = new JLabel ("These are the potential problems we found with your system:");
        jcomp7 = new JList (jcomp7Items);

        //adjust size and set layout
        setPreferredSize (new Dimension (930, 677));
        setLayout (null);

        //add components
        add (jcomp1);
        add (jcomp2);
        add (Solutions);
        add (jcomp4);
        add (jcomp5);
        add (jcomp6);
        add (jcomp7);

        //set component bounds (only needed by Absolute Positioning)
        jcomp1.setBounds (15, 490, 480, 140);
        jcomp2.setBounds (10, 580, 910, 135);
        Solutions.setBounds (505, 30, 413, 600);
        jcomp4.setBounds (35, 10, 170, 65);
        jcomp5.setBounds (0, 0, 935, 25);
        jcomp6.setBounds (35, 90, 445, 25);
        jcomp7.setBounds (35, 110, 440, 375);
    }


    public static void main (String[] args) {
        JFrame frame = new JFrame ("PlatypusGUI");
        frame.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
        frame.getContentPane().add (new PlatypusGUI());
        frame.pack();
        frame.setVisible (true);
    }
}
